---
title: "Replication of Study 1 by Krauss & Wang (2003, Journal of Experimental Psychology)"
author: "Bendix Kemmann (kemmann@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

<!-- [No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.   -->

### A short justification for this choice of experiment in terms of my research interests or research program (1 paragraph)

In my own research in the Philosophy Department, I'm studying how the choice of representation system, i.e. the syntactic and semantic rules that govern how representations are constructed and interpreted, might affect how demanding (in a broadly speaking cognitive or practical rather than an abstract computational sense) it is to carry out reasoning tasks. For example, different notation systems for natural numbers give rise to different procedures for carrying out arithmetic calculations, and these appear demanding to different degrees. Similar things can be said about diagrammatic versus sentential representation systems.

In their study, @krauss2003 investigated how different representations of the famous Monty Hall problem affect the rate of correct answers as well as the rate of correct justifications given for those answers. @krauss2003 predicted that a presentation of the problem that involves four features intended to elicit a correct intuitive solution to the problem would be more likely to lead to correct responses than a control version that lacked these features. The four features, which @krauss2003 call 'psychological elements', were: (1) prompting the participants to adopt the perspective of Monty rather than the contestant, (2) prompting the participants to use less than full information, (3) prompting participants to construct 'mental models' of the scenario, and (4) prompting participants to construe the problem in terms of natural frequencies rather than probabilities.

While the study doesn't directly bear on my research -- it doesn't explicitly consider formal features of representation systems but rather invokes posited psychological mechanisms (the term 'mechanism' should be understood loosely) -- it is the rescue project that most closely relates to my interests. If we zoom out enough, the underlying question is the same: how does how we represent a reasoning task affect how easy it is for us to solve it? Different presentations of the same problem might engage different cognitive mechanisms, some of which may be easier and less error prone than others. Another reason why I'm drawn to this rescue project is that I've encountered the Monty Hall problem before in my Bayesian philosophy of science and decision theory classes. There, the problem was approached from a formal, mathematical perspective. However, what is so interesting about the Monty Hall problem is arguably not the normative question of what the correct solution to it is, but rather the descriptive question of why so many people -- including highly educated people -- find it so difficult to arrive at this solution. While the @krauss2003 study doesn't actually directly answer this question, as it doesn't identify the cognitive processes involved in successful or unsuccessful solution attempts, it may nonetheless suggest that many people make reasoning mistakes that can be avoided by framing the problem in the right way.

### A description of the stimuli and procedures that will be required to conduct this experiment, and what the challenges will be (1-2 paragraphs)

In experiment 1, subjects will be presented with one of three versions of the Monty Hall problem: a) a control version (Figure 3 in the original paper), b) a 'Guided intuition' version in which all four features are added to the control version (Figure 4 in the original paper), and c) a 'One-Door' version in which only one feature, the 'less-is-more' manipulation, is added (Appendix C in the original paper). In the original experiment, participants were tested in groups of five. Somewhat frustratingly, the original paper doesn't specify how much time participants had, how the sessions were conducted, or why the group size was capped at 5. I assume that participants had as much time as they needed to complete the worksheet they were given (presumably capped at 30 minutes or so). We know that each participant was given one worksheet corresponding to their assigned group (a, b, or c). I also assume that no further verbal explanation or clarification was provided during the session, i.e. participants responded to the worksheet quietly on their own -- otherwise the experimenter would be interfering by altering the representation of the problem. After excluding participants that had seen the Monty Hall problem before, Participants' responses were classified into 'stayers' (incorrect) and 'switchers' (correct), and the switchers' justifications for their answer were classified into one of three groups, depending on whether the experimenter believed the participant exhibited full insight into the mathematical structure of the problem, had the right intuition but couldn't provide a correct proof, or switched randomly.

If the rescue attempt involves collecting new data, then I believe it would be better to conduct data in person rather than using crowd-sourced participants online. The problem with having participants work through the worksheets online is simply that they may easily search for the Monty Hall problem and be exposed to different representations of it in the process. Even though we can check the justification they provide, we can't guarantee that this justification is their own or that they haven't been exposed to a different version of the problem. The best we could do, I suppose, is ask them to state whether they have solved the problem without looking it up elsewhere, and take their word for it. The original study also involved 149 participants. If I attempt to collect new data in person and we aim for a similar sample size, this could be quite time-consuming. We would also have to determine where to obtain funding to pay participants. (However, I would also be perfectly okay with merely reproducing the results using the existing data sets, if this is okay with the PSYCH 251 teaching team.) Another, but arguably smaller issue is that the original experiment 1 in @krauss2003 was conducted with German university students using German prompts. While their paper includes English translations which can easily be used for the replication study, strictly speaking, we won't be using the same representations. Having said this, it's unclear that the difference in language makes a significant difference to how the problem is solved, as the mathematical structure of the problem is invariant across the two natural language versions.

<!-- A link to the repository and to the original paper (as hosted in your repo). The goal is that we should be able to click on these links and review that your repo is formatted right and look at the original paper.  -->

### Link to the repository

<https://github.com/psych251/krauss2003_rescue>

### Link to the original Krauss & Wang (2003) paper

<https://github.com/psych251/krauss2003_rescue/blob/main/original_paper/krauss2003.pdf>


## Summary of prior replication attempt

Based on the prior write-up, describe any differences between the original and 1st replication in terms of methods, sample, sample size, and analysis. Note any potential problems such as exclusion rates, noisy data, or issues with analysis. 

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

How much power does your planned sample have for original effect? For an attenuated effect that is half the size of the original? 

(If power analysis is not possible or precise, discuss more fully how you determined a sample size that would be sufficient for rescue.)

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Controls

What attention checks, positive or negative controls, or other quality control measures are you adding so that a (positive or negative) result will be more interpretable?


### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study and 1st replication

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Results of control measures

How did people perform on any quality control checks or positive and negative controls? 

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Three-panel graph with original, 1st replication, and your replication is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

## Mini meta analysis
Combining across the original paper, 1st replication, and 2nd replication, what is the aggregate effect size? 

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
